### ISSUE TITLE
Server Port should be dynamic

### ISSUE THREAD

**Issue by Vinidel** [Carnevali/testing-api-with-nodejs#2]
In app.js the PORT is set with a hardcoded number `7000`

Instead get the value from a environment variable and if the value is undefined set to 7000

```Javascript
const PORT = process.env.PORT || 7000
.
.
.
app.set('port', PORT);
```

This way you can set the server port dynamically, lets say you are running multiple docker containers with node.js servers, each one will be running in a port. Therefore you can set an environment variable called `PORT` and the app will use that variable to start the server, so servers don't run in the same port.

Cheers,
Vinny.

**Comment by Carnevali** [comment]
Done!
