### ISSUE TITLE
Mutating requests

### ISSUE THREAD

**Issue by Vinidel** [Carnevali/testing-api-with-nodejs#3]
Hey, a challenge for you. 

I would like you  to log all requests in the terminal, you can use `console.log` and also I want you to add a value to the request headers.
Have a look at middlewares and how they work, middlewares are often used when working with NodeJS.

For this, please create a branch with the issue number as its name, when you are done or want me to have a look, create a pull request and assign me as reviewer. You can do this even if you have any questions.

Once everything is good, I'll approve it and we can merge it to master.

Cheers,
Vinny.

**Comment by Vinidel** [comment]
Branch name should be `API-3`

**Comment by FelipeCarnevali** [comment]
Okay. Great, I will make this. 

Cheers,
Felipe Luiz Carnevali

**Comment by Carnevali** [comment]
Hey Mate,

I finished. Look and see if that what I did is correct.

Cheers

Felipe Luiz Carnevali
